### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by GisRookie** [OpenGVLab/InternGPT#10]
After installation according to guidiance, i run the follow commands, then the error happen.
python -u app.py --load "HuskyVQA_cuda:0,SegmentAnything_cuda:0,ImageOCRRecognition_cuda:0" --port 3456

Looking in indexes: http://mirrors.ops.ctripcorp.com/pypi-latest/simple
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-req-build-tcy8m3_g
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-req-build-tcy8m3_g
  Resolved https://github.com/facebookresearch/detectron2.git to commit 3c7bb714795edc7a96c9a1a6dd83663ecd293e36
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  _ python setup.py egg_info did not run successfully.
  _ exit code: 1
  __> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-tcy8m3_g/setup.py", line 10, in <module>
          import torch
        File "/home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/__init__.py", line 191, in <module>
          _load_global_deps()
        File "/home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/__init__.py", line 153, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/home/powerop/work/conda/envs/igpt/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

_ Encountered error while generating package metadata.
__> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "app.py", line 28, in <module>
    from iGPT.controllers import ConversationBot
  File "/home/powerop/work/gongsong/InternGPT/iGPT/__init__.py", line 1, in <module>
    from .models import *
  File "/home/powerop/work/gongsong/InternGPT/iGPT/models/__init__.py", line 1, in <module>
    from .image import (InstructPix2Pix, ImageText2Image,
  File "/home/powerop/work/gongsong/InternGPT/iGPT/models/image.py", line 2, in <module>
    import torch
  File "/home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/powerop/work/conda/envs/igpt/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/powerop/work/conda/envs/igpt/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

**Comment by liu-zhy** [comment]
Do you add CUDA_HOME into the environment variable (PATH)?

**Comment by GisRookie** [comment]
thanks your reply, i resolve it
