### ISSUE TITLE
follow readme.md ，I got this error when I try to start a gradio service

### ISSUE THREAD

**Issue by iwaitu** [OpenGVLab/InternGPT#14]
```
Traceback (most recent call last):
  File "E:\github\InternGPT\app.py", line 28, in <module>
    from iGPT.controllers import ConversationBot
  File "E:\github\InternGPT\iGPT\__init__.py", line 1, in <module>
    from .models import *
  File "E:\github\InternGPT\iGPT\models\__init__.py", line 1, in <module>
    from .image import (InstructPix2Pix, ImageText2Image,
  File "E:\github\InternGPT\iGPT\models\image.py", line 8, in <module>
    import cv2
  File "C:\Users\iwaitu\anaconda3\envs\igpt\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\iwaitu\anaconda3\envs\igpt\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\iwaitu\anaconda3\envs\igpt\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\iwaitu\anaconda3\envs\igpt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\iwaitu\anaconda3\envs\igpt\lib\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
```

**Comment by liu-zhy** [comment]
Could you share more information about environment? 

Given this error, we recommend you refer to https://stackoverflow.com/questions/72706073/attributeerror-partially-initialized-module-cv2-has-no-attribute-gapi-wip-gs.
