### ISSUE TITLE
在gradio的demo上不管跑什么模块，终端始终都报同样的错误。

### ISSUE THREAD

**Issue by dengtianbi** [OpenGVLab/InternGPT#19]
在gradio的demo上不管跑什么模块，终端都报同样的错误。
Traceback (most recent call last):
  File "/mnt/ai212/workspace/dengtb/anaconda3/envs/ichat/lib/python3.8/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/ai212/workspace/dengtb/anaconda3/envs/ichat/lib/python3.8/site-packages/gradio/blocks.py", line 1323, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/mnt/ai212/workspace/dengtb/anaconda3/envs/ichat/lib/python3.8/site-packages/gradio/blocks.py", line 1257, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/mnt/ai212/workspace/dengtb/anaconda3/envs/ichat/lib/python3.8/site-packages/gradio/components.py", line 4629, in postprocess
    assert isinstance(
AssertionError: Expected a list of lists or list of tuples. Received: None

**Comment by liu-zhy** [comment]
Could you mind sharing more information like environment and start command about this issue? 
 
We also need the your operation steps, so that we can reproduce your problem.

**Comment by zhangzhengyi12** [comment]
same error

**Comment by Droliven** [comment]
same error. Do you solved it?
