### ISSUE TITLE
下载时候呢，开clash 会报错，不开也报错

### ISSUE THREAD

**Issue by lassdfsdf** [OpenGVLab/InternGPT#26]
开VPN 时候报错如下：
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/draggan/
不开VPN 下载一会报错如下：
下载大概不到一分钟，就速度为0 ，就报错如下
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\draggan\lib\site-packages\pip\_vendor\urllib3\response.py", line 437, in _error_catcher
    yield
  File "C:\Users\Administrator\.conda\envs\draggan\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\Administrator\.conda\envs\draggan\lib\site-packages\pip\_vendor\urllib3\response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\Administrator\.conda\envs\draggan\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)

**Comment by liu-zhy** [comment]
Sorry. I can not give you soulution with insufficient information. Could you share your environment and operations so that I can reproduce this issue.
