### ISSUE TITLE
if resolved_archive_file.endswith(".index"): AttributeError: 'list' object has no attribute 'endswith

### ISSUE THREAD

**Issue by dizhenx** [OpenGVLab/InternGPT#44]
Traceback (most recent call last):
  File "/mnt/data/creative/InternGPT/app.py", line 225, in <module>
    bot = ConversationBot(load_dict=load_dict, e_mode=args.e_mode)
  File "/mnt/data/creative/InternGPT/iGPT/controllers/ConversationBot.py", line 144, in __init__
    self.models[class_name] = globals()[class_name](device=device,e_mode=e_mode)
  File "/mnt/data/creative/InternGPT/iGPT/models/husky.py", line 369, in __init__
    download_if_not_exists(base_path="model_zoo/llama", 
  File "/mnt/data/creative/InternGPT/iGPT/models/husky.py", line 359, in download_if_not_exists
    apply_delta(output_dir, new_path, delta_path)
  File "/mnt/data/creative/InternGPT/iGPT/models/husky_src/load_ckpt.py", line 11, in apply_delta
    base = AutoModelForCausalLM.from_pretrained(base_model_path, torch_dtype=torch.float16,from_tf=True,low_cpu_mem_usage=True)
  File "/mnt/data/creative/miniconda3/envs/internGPT/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/data/creative/miniconda3/envs/internGPT/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2753, in from_pretrained
    if resolved_archive_file.endswith(".index"):
AttributeError: 'list' object has no attribute 'endswith'

When run python -u app.py --load "HuskyVQA_cuda:1,SegmentAnything_cuda:2,ImageOCRRecognition_cuda:3" --port 7863 -e，it happens
How to solve it？

**Comment by G-z-w** [comment]
Please make sure these folder model_zoo/llama, and model_zoo/llama_7B_hf contain the correct checkpoint. You can try removing 
the folders and running the code again. The app will automatically download the checkpoint and convert it to the hf format.
